name: secret-scan

on:
  pull_request:
  workflow_call:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    name: gitleaks
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  git-secrets:
    runs-on: ubuntu-latest
    name: git-secrets
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install git-secrets
        env:
          # Pin to git-secrets
          TARGET_HASH: ad82d68ee924906a0401dfd48de5057731a9bc84 # 1.3.0
        run: |
          git init /tmp/git-secrets
          git -C /tmp/git-secrets remote add origin https://github.com/awslabs/git-secrets.git
          git -C /tmp/git-secrets fetch --depth 1 origin "$TARGET_HASH"
          git -C /tmp/git-secrets checkout --detach FETCH_HEAD
          sudo make -C /tmp/git-secrets install
      - name: Scan
        run: |
          git secrets --register-aws
          git secrets --scan-history
